//! Consolidated "anchor" rules for the templates category.
//!
//! Each entry is a no-op metadata holder generated by [`crate::anchor_rule!`].
//! The real validation for every rule ID below happens elsewhere in the
//! pipeline; the inline comment on each invocation says where. These structs
//! exist so the rule IDs are registered (for `--list-rules`, include/exclude
//! configuration, and the registration-completeness snapshot test).
//!
//! Previously each of these was its own ~40-line file with five hand-written
//! metadata methods; they were consolidated here to remove that duplication.

use crate::rules::Severity;

// --- Diagnostic / infrastructure anchors -----------------------------------

// Parse errors are emitted directly by the parser and tagged with this ID.
crate::anchor_rule!(
    E0000,
    "Parsing error found when parsing the template",
    "Checks for JSON/YAML formatting errors in your template",
    Severity::Error
);

// Emitted when a rule itself fails while processing the template.
crate::anchor_rule!(
    E0002,
    "Error processing rule on the template",
    "Errors found when processing a rule on the template",
    Severity::Error
);

// Emitted for errors originating from the cfn-lint configuration.
crate::anchor_rule!(
    E0003,
    "Error with cfn-lint configuration",
    "Error as a result of the cfn-lint configuration",
    Severity::Error
);

// --- cfn-lint keyword dispatch anchors --------------------------------------

// Dispatched by the schema validator to child rules via `cfn-lint` keywords.
crate::anchor_rule!(
    E1101,
    "Validate an item against additional checks",
    "Use supplemental logic to validate properties against cfn-lint keywords",
    Severity::Error
);

// Parent rule for the `format` keyword; format checks are performed by
// `validate_format` in `jsonschema/keywords`. The E115x rules below map to
// specific format strings handled by the same code.
crate::anchor_rule!(
    E1103,
    "Validate the format of a value",
    "Parent rule for validating the format keyword in schemas",
    Severity::Error
);

// --- Format-string anchors (handled by jsonschema/keywords validate_format) --

// format: AWS::EC2::SecurityGroup::Id
crate::anchor_rule!(
    E1150,
    "Validate security group format",
    "Security groups must ref/getatt to a security group or match the valid pattern",
    Severity::Error
);

// format: AWS::EC2::VPC::Id
crate::anchor_rule!(
    E1151,
    "Validate VPC id format",
    "Check that a VPC id matches a pattern",
    Severity::Error
);

// format: AWS::EC2::Image::Id
crate::anchor_rule!(
    E1152,
    "Validate AMI id format",
    "Check that an AMI id matches a pattern",
    Severity::Error
);

// format: AWS::EC2::SecurityGroup::GroupName
crate::anchor_rule!(
    E1153,
    "Validate security group name",
    "Security group names must match the valid pattern",
    Severity::Error
);

// format: AWS::EC2::Subnet::Id
crate::anchor_rule!(
    E1154,
    "Validate VPC subnet id format",
    "Check that a VPC subnet id matches a pattern",
    Severity::Error
);

// format: AWS::Logs::LogGroup::Name
crate::anchor_rule!(
    E1155,
    "Validate CloudWatch logs group name",
    "Check that a CloudWatch log group name matches a pattern",
    Severity::Error
);

// format: AWS::IAM::Role::Arn
crate::anchor_rule!(
    E1156,
    "Validate IAM role ARN format",
    "Validate IAM role ARN for ref/getatt and string values",
    Severity::Error
);

// --- Rules-section anchors (schema-driven validation of the Rules section) ---

crate::anchor_rule!(
    E1700,
    "Rules have the appropriate configuration",
    "Making sure the Rules section is properly configured",
    Severity::Error
);

crate::anchor_rule!(
    E1701,
    "Validate the configuration of Assertions",
    "Make sure the Assert value in a Rule is properly configured",
    Severity::Error
);

crate::anchor_rule!(
    E1702,
    "Validate the configuration of Rules RuleCondition",
    "Make sure the RuleCondition in a Rule is properly configured",
    Severity::Error
);

// --- Resolved-value anchors (schema validator resolves the function, then
//     validates the resolved value against the schema) -----------------------

crate::anchor_rule!(
    W1030,
    "Validate resolved Ref values",
    "Resolve the Ref and then validate the values against the schema",
    Severity::Warning
);

crate::anchor_rule!(
    W1031,
    "Validate resolved Fn::Sub values",
    "Resolve the Fn::Sub and then validate the values against the schema",
    Severity::Warning
);

crate::anchor_rule!(
    W1032,
    "Validate resolved Fn::Join values",
    "Resolve the Fn::Join and then validate the values against the schema",
    Severity::Warning
);

crate::anchor_rule!(
    W1033,
    "Validate resolved Fn::Split values",
    "Resolve the Fn::Split and then validate the values against the schema",
    Severity::Warning
);

crate::anchor_rule!(
    W1034,
    "Validate resolved Fn::FindInMap values",
    "Resolve the Fn::FindInMap and then validate the values against the schema",
    Severity::Warning
);

crate::anchor_rule!(
    W1035,
    "Validate resolved Fn::Select values",
    "Resolve the Fn::Select and then validate the values against the schema",
    Severity::Warning
);

crate::anchor_rule!(
    W1036,
    "Validate resolved Fn::GetAZs values",
    "Resolve the Fn::GetAZs and then validate the values against the schema",
    Severity::Warning
);

#[cfg(test)]
mod tests {
    use super::*;
    use crate::ast::{AstNode, ObjectNode, Span as AstSpan};
    use crate::jsonschema::cfn_lint_keyword::CfnLintRule;
    use crate::template::Template;

    #[test]
    fn test_metadata_and_noop() {
        // Spot-check id/severity mapping and that anchors are no-ops. The full
        // set of registered IDs is asserted by tests/rule_registration.rs.
        assert_eq!(E1150.id(), "E1150");
        assert_eq!(E1150.severity(), Severity::Error);
        assert_eq!(W1030.id(), "W1030");
        assert_eq!(W1030.severity(), Severity::Warning);

        let root = AstNode::Object(ObjectNode {
            entries: Vec::new(),
            span: AstSpan::default(),
        });
        let tmpl = Template::from_ast(&root).unwrap();
        assert!(E1150.validate_template(&tmpl, &root).is_empty());
        assert!(W1030.validate_template(&tmpl, &root).is_empty());
    }
}
