- id: cfn-python-lint
  name: AWS CloudFormation Linter
  description: 'cfn-lint is a tool for finding issues with CloudFormation templates'
  entry: cfn-lint
  language: python
  files: \.(json|yaml|yml)$
- id: cfn-lint # we have removed most identifications to cfn-python-lint
  name: AWS CloudFormation Linter
  description: 'cfn-lint is a tool for finding issues with CloudFormation templates'
  entry: cfn-lint
  language: python
  files: \.(json|yaml|yml)$
- id: cfn-lint-rc # Provide a configuration to use with .cfnlintrc
  name: AWS CloudFormation Linter
  description: 'cfn-lint is a tool for finding issues with CloudFormation templates'
  entry: cfn-lint
  language: python
  pass_filenames: false
