version: 0.2
phases:
  install:
    commands:
      - pip install tox
  build:
    commands:
      - docker run -i --rm -v "${PWD}:/cfnlint" -w /cfnlint python:2.7-alpine3.7 pip install tox; tox -e py27
      - docker run -i --rm -v "${PWD}:/cfnlint" -w /cfnlint python:3.6-alpine3.7 pip install tox; tox -e py36, pylint
