name: Bug report
description: Create a report to help us improve cfn-lint

body:
  - type: markdown
    attributes:
      value: |
        Thanks for taking the time to fill out this bug report! Try to include as much information as you can.

        For reference, the current version of cfn-lint is <img src="https://badge.fury.io/py/cfn-lint.svg" />.

        Cfn-lint uses the [CloudFormation Resource Specifications](https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/cfn-resource-specification.html) as the base to do validation. These files are included as part of the application version. Please update to the latest version of `cfn-lint` or update the spec files manually (`cfn-lint -u`)
  - type: input
    attributes:
      label: CloudFormation Lint Version
      placeholder: Run `cfn-lint --version` to get the `cfn-lint` version
    validations:
      required: true
  - type: input
    attributes:
      label: What operating system are you using?
      description: "For example: Mac, Windows, Ubuntu."
    validations:
      required: true
  - type: markdown
    attributes:
      value: |
        ## Details
  - type: textarea
    attributes:
      label: Describe the bug
      description: A clear and concise description of what the bug is.
    validations:
      required: true
  - type: textarea
    attributes:
      label: Expected behavior
      description: A clear and concise description of what you expected to happen.
    validations:
      required: true
  - type: textarea
    attributes:
      label: Reproduction template
      description: Provide the template used to reproduce this bug
      placeholder: |
        ```yaml
        AWSTemplateFormatVersion: "2010-09-09"
        ...
        ```
    validations:
      required: true
