blank_issues_enabled: true
contact_links:
  - name: I want help working with cfn-lint
    url: https://discord.gg/KENDm6DHCv
    about: Check out the `Need Help?` channels on CloudFormation's community Discord to ask your questions about using cfn-lint
