//! Consolidated "anchor" rules for the conditions category.
//!
//! Each entry is a no-op metadata holder generated by [`crate::anchor_rule!`].
//! The real structural validation of these condition functions is performed by
//! the schema pipeline / engine condition checks (see the inline comment on
//! each invocation). These structs exist so the rule IDs are registered.

use crate::rules::Severity;

// Fn::Equals structure (list of exactly two elements) is validated by the
// schema pipeline's fn_equals keyword (maps to "E8003").
crate::anchor_rule!(
    E8003,
    "Check Fn::Equals structure for validity",
    "Check Fn::Equals is a list of two elements",
    Severity::Error
);

// Fn::And structure (2-10 condition values) is validated by the schema
// pipeline's fn_condition keyword (maps to "E8004").
crate::anchor_rule!(
    E8004,
    "Check Fn::And structure for validity",
    "Check Fn::And is a list of two to ten condition values",
    Severity::Error
);

// Fn::Not structure (list of one element) is validated by the engine's
// validate_condition_functions.
crate::anchor_rule!(
    E8005,
    "Check Fn::Not structure for validity",
    "Check Fn::Not is a list of one element",
    Severity::Error
);

// Fn::Or structure (2-10 condition values) is validated by the engine's
// validate_condition_functions.
crate::anchor_rule!(
    E8006,
    "Check Fn::Or structure for validity",
    "Check Fn::Or is a list of two to ten condition values",
    Severity::Error
);

#[cfg(test)]
mod tests {
    use super::*;
    use crate::jsonschema::cfn_lint_keyword::CfnLintRule;
    use crate::parser;
    use crate::template::Template;

    #[test]
    fn test_metadata_and_noop() {
        assert_eq!(E8003.id(), "E8003");
        assert_eq!(E8006.severity(), Severity::Error);

        // Malformed condition functions are ignored by the anchors themselves;
        // the schema pipeline/engine performs the real checks.
        let yaml = br#"
Conditions:
  Bad:
    Fn::Equals:
      - a
      - b
      - c
Resources:
  B:
    Type: AWS::S3::Bucket
"#;
        let ast = parser::parse(yaml).unwrap();
        let tmpl = Template::from_ast(&ast).unwrap();
        assert!(E8003.validate_template(&tmpl, &ast).is_empty());
    }
}
