name: "[CD] Upload to pypi"

on:
  release:
    types: [published]

permissions:
  contents: read
  id-token: write

jobs:
  deploy:
    runs-on: ubuntu-latest
    if: github.repository == 'aws-cloudformation/cfn-lint'
    steps:
      - name: Set up Python
        uses: actions/setup-python@v6
        with:
          python-version: "3.13"
      - name: Get version
        id: getversion
        run: |
          echo -n "version=" >> "$GITHUB_OUTPUT"
          echo ${{ github.ref_name }}|cut -c2- >> "$GITHUB_OUTPUT"
      - name: Download release
        env:
          GH_TOKEN: ${{ github.token }}
        run: |
          gh release download ${{ github.ref_name }} -p 'cfn_lint-*' -R ${{ github.repository }}
          mkdir -p dist
          cp cfn_lint-${{ steps.getversion.outputs.version }}.tar.gz cfn_lint-${{ steps.getversion.outputs.version }}-py3-none-any.whl dist/
      - name: Publish to PyPI
        uses: pypa/gh-action-pypi-publish@release/v1
