name: "[CI] Upload PR coverage"

on:
  workflow_run:
    workflows:
      - \[CI\] Test PR
    types:
      - completed

jobs:
  upload-coverage:
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Download All Artifacts
        uses: actions/download-artifact@v4
        with:
          pattern: coverage-*
          merge-multiple: true

      - name: Upload coverage report
        if: '!cancelled()'
        uses: codecov/codecov-action@v3
        with:
          override_commit: ${{ github.event.workflow_run.head_sha }}
          override_pr: ${{ github.event.workflow_run.pull_requests[0].number }}
          token: ${{ secrets.CODECOV_TOKEN }}
          files: "coverage-*.xml"
          fail_ci_if_error: true
          verbose: true
