name: Automated Maintenance v1
on:
  schedule:
    - cron: "0 8,20 * * *"
  workflow_dispatch:

permissions:
  contents: write
  pull-requests: write
jobs:
  job:
    runs-on: ubuntu-latest
    if: github.repository == 'aws-cloudformation/cfn-lint'
    steps:
      - uses: actions/checkout@v7
        with:
          ref: "main"
      - uses: actions/setup-python@v7
        with:
          python-version: 3.13
      - id: maintenance
        run: |
          pip install -e .
          pip install -r requirements/dev.txt
          cfn-lint --update-iam-policies
          cfn-lint --update-specs --force
          scripts/update_specs_from_pricing.py
          scripts/update_schemas_from_aws_api.py
          cfn-lint --update-documentation
          echo "date=$(date +'%Y-%m-%d')" >> $GITHUB_OUTPUT
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
      - uses: peter-evans/create-pull-request@v8
        with:
          branch: create-pull-request/maintenance-v1
          commit-message: |
            Update CloudFormation schemas to ${{ steps.maintenance.outputs.date }}
          body: |
            - Update CloudFormation schemas to ${{ steps.maintenance.outputs.date }}

            Automated changes by [create-pull-request](https://github.com/peter-evans/create-pull-request) GitHub action
          delete-branch: true
          title: Update CloudFormation schemas to ${{ steps.maintenance.outputs.date }}
